### ISSUE TITLE
Launch Instructions in README?

### ISSUE THREAD

**Issue by iristao** [taywong00/Jithub#3]
I believe that we also need to include launch instructions in our README file? Right now I only see descriptions. 
i.e.:

1. Enter java Woo, the grid will appear. 
2. Select a tile by entering its labelled letter (ie. a,b,c,d,...)
3. A prompt will pop up asking you what you want to do with this tile
4. Select an option by entering number 1 or 2 (either 1. Flip or 2. Take Notes)
5. (take notes) type in a line of notes and hit Enter to exit the note taking mode
6. Select your next tile...

PS. I am not sure if ^this is what we need, if you think "launch instructions" means something else, feel free to modify mine.

**Comment by taywong00** [comment]
yep i think these are fine. if anything it would specify something like evnter java Woo.java in the terminal or something
